title: Sangeeth Nandakumar
author: Sangeeth Nandakumar
email: sangeethnandakumarwork@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Welcome to my Github page where you can find and use my open source packages for any projects open-source or commercial.
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: /

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Sangeeth Nandakumar
  tagline: "Developer. Open Source"
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  showPicker: false

  # generate social links in footer
  social_links:
    #twitter: thelehhman
    github:  sangeethnandakumar
    linkedIn: in/sangeethnandakumar
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
